INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('6', 'Catering', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('9', 'Christmas Specials', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('13', 'Packed Food', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('14', 'Raya 2018 Catering', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('17', 'Events & Gifting', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('18', 'CNY Cookies', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('19', 'CNY Events', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('20', 'CNY Hampers', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('21', 'Flowers', '17');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('22', 'Hampers', '17');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('23', 'Mooncake', '17');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('26', 'Fruit', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('27', 'CNY Oranges', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('28', 'Fruits Package', '26');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('29', 'Whole Fruits', '26');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('30', 'Furniture', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('31', 'Office Chair', '30');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('32', 'Office Desk', '30');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('33', 'Office Set', '30');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('34', 'Office Sofa', '30');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('35', 'Storage Space', '30');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('36', 'Pantry', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('37', 'Air Fresheners', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('39', 'Biscuits & Crackers', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('40', 'Bread & Eggs', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('41', 'Candies', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('42', 'Carbonated & Energy Drinks', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('44', 'Cereals & Grains', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('45', 'Chocolate & Malted Drinks', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('46', 'Chocolate & Snacks', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('47', 'Cleaning Chemicals', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('48', 'Cleaning Tools', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('49', 'Coffee', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('50', 'Cooking Ingredients', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('51', 'Dishwash & Detergents', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('52', 'Electrical Appliances', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('53', 'Flavoured Drinks', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('54', 'Handwash', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('55', 'Insecticides', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('56', 'Instant Food', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('57', 'Jam & Spreads', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('58', 'Kitchen Utensils', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('59', 'Milk & Dairy', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('60', 'Water', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('61', 'Pharmaceuticals', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('62', 'Powdered Drinks & Cordials', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('63', 'Sauce & Condiments', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('64', 'Storage & Plastics', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('65', 'Sugar & Creamer', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('66', 'Tea', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('67', 'Facial Tissues', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('68', 'Waste Management', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('69', 'Stationery', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('71', 'Art Supplies', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('72', 'Batteries', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('74', 'Blank Medias', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('77', 'Calculators', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('79', 'Clips & Binders', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('80', 'Cutters', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('82', 'Desk Organizers', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('84', 'Display Boards & Stands', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('86', 'Envelopes', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('88', 'Erasers & Corrections', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('90', 'Files & Filing', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('92', 'Glues', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('93', 'Highlighters', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('94', 'Labels & Tags', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('95', 'Magnets', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('96', 'Markers', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('97', 'Markers - Permanent', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('98', 'Markers - Whiteboard', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('99', 'Miscellaneous', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('101', 'Name Tag Holders', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('102', 'Notebooks & Writing Pads', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('103', 'Office Machines & Supplies', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('104', 'Paper', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('105', 'Paper,A3 Paper', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('106', 'Paper,A4 Paper', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('107', 'Pencils', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('108', 'Pens', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('110', 'Post-it & Sticky Notes', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('112', 'Rulers', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('113', 'Scissors', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('114', 'Stamp Pads', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('116', 'Staplers & Punchers', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('117', 'Storage & Organization', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('119', 'Tapes & Adhesives', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('120', 'Whiteboards', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('121', 'Technology', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('123', 'Computer Accessories', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('124', 'Laptop', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('125', 'Monitor', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('127', 'Printer Cartridges', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('128', 'RAM', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('129', 'Software', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('130', 'Storage', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('137', 'Gift Cards & Vouchers', '17');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('139', 'Bins', '30');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('142', 'Paper - Other Sizes', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('146', 'Canapé', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('147', 'Desk Organisers', '30');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('148', 'Fruit Juice', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('150', 'Stamps', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('151', 'Projectors', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('152', 'Audio', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('153', 'Wearables', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('154', 'Ice Creams', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('155', 'Camera', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('156', 'Electrical Products', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('157', 'Air Purifier', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('158', 'Blender', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('159', 'Coffee Maker', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('160', 'Cooler Fan', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('161', 'Fan', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('162', 'Freezer', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('163', 'Kettle', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('164', 'Microwave Oven', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('165', 'Refrigerator', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('166', 'Toaster', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('167', 'Vacuum', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('168', 'Festive', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('169', 'Water Dispensers', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('170', 'Water Purifiers', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('171', 'CNY Catering', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('173', 'Corporate Gifts & Premium', '17');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('174', 'CNY Snacks', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('175', 'Toilet Paper', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('176', 'Kitchen Towels', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('177', 'Tables', '30');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('179', 'General Catering', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('180', 'Mobile Phones', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('181', 'Packed Fruits/Seeds', '26');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('182', 'Tea Break', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('183', 'Finger Food', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('184', 'Dome & Course', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('185', 'Half Day Package', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('186', 'Banquet & Gala', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('190', 'Cakes & Buns', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('192', 'Fees', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('193', 'Delivery Fees', '192');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('194', 'Catering Charges', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('195', 'Service Fees', '192');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('196', 'Massage Equipments', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('198', 'Raya', '17');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('199', 'Fast Food', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('200', 'Events', '17');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('201', 'Toy Gifts', '17');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('202', 'Services', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('203', 'Cleaning Sevices', '202');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('204', 'Specialist Services', '202');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('205', 'Hardwares & Tools', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('206', 'Power Tools', '205');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('207', 'Ladders', '205');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('208', 'Apparels', NULL);
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('209', 'Workwear', '208');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('210', 'Training Services', '202');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('211', 'Trolleys', '205');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('212', 'Safety Wear', '208');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('213', 'Bags', '208');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('214', 'Electrical Pots', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('215', 'Xmas Cake & Cookies', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('216', 'Sports Equipments', '208');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('217', 'Printing Services', '202');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('218', 'Tablet', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('219', 'Additional Requests', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('220', 'Management Fees', '192');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('221', 'Packing Fees', '192');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('222', 'Installation Fees', '192');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('223', 'Purchasing Fees', '192');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('224', 'Deposit', '192');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('225', 'Packing Tools', '205');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('226', 'Pantry Accessories', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('227', 'Personal Hygiene', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('228', 'Needlework', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('229', 'Alcohol', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('230', 'Cushions', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('231', 'Indoor Plant & Pots', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('232', 'Raya Hampers', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('233', 'Kuih', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('234', 'Books', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('235', 'E-Books', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('236', 'Buffet', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('237', 'Gift Boxes', '17');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('238', 'Media Services', '202');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('239', 'Ramadan Delights', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('240', 'Raya Gifts', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('241', 'Raya Flowers', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('242', 'TV', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('243', 'Rental Services', '202');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('244', 'Claw Machines', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('245', 'Electronics Darts', '156');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('246', 'Raya Catering', '168');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('247', 'Online Services', '202');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('248', 'Safety Equipments', '36');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('249', 'Legal Fees', '192');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('250', 'Beauty Products', '17');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('253', 'Desktop', '121');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('254', 'Beverages', '6');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('255', 'Rental Fees', '192');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('256', 'Accessories', '69');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('257', 'Sports Apparel', '208');
INSERT INTO `categories` (`id`, `title`, `parent_id`) VALUES ('258', 'Gardening Equipments', '205');
